stages:
  - build
  - test
  - deploy

build_job:
  stage: build
  script:
    - echo "Building the project..."
    - # 여기에 빌드 명령어를 추가하세요

run_python_script:
  stage: build
  script:
    - echo "Running jobfile_search_and_run.py..."
    - python jobfile_search_and_run.py
    - git config --global user.email "you@example.com"
    - git config --global user.name "Your Name"
    - git add *.csv
    - git commit -m "Add new CSV files"
    - git push https://gitlab-ci-token:${GITLAB_TOKEN}@<repository-url>.git HEAD:<branch-name>

test_job:
  stage: test
  script:
    - echo "Running tests..."
    - # 여기에 테스트 명령어를 추가하세요

deploy_job:
  stage: deploy
  script:
    - echo "Deploying the project..."
    - # 여기에 배포 명령어를 추가하세요
